# CLASS-1

NUMPY Package

In [2]:
import numpy as np  # we can get many inbuilt function in this numpy library
a = [1,2,3,4,5]
arr = np.array(a)  # to convert a list to an array
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
summ = np.sum(arr)
print("The sum of the given numbers in the arrays are:", summ)

avg = np.mean(arr)
print("The average of the given numbers in the arrays are:", avg)

varience = np.var(arr)
print("The varience of the given numbers in the arrays are:", varience)

maxx = np.max(arr)
print("The maximum number present in the list is:", maxx)

minn = np.min(arr)
print("The minumum number present in the list is:", minn)

The sum of the given numbers in the arrays are: 15
The average of the given numbers in the arrays are: 3.0
The varience of the given numbers in the arrays are: 2.0
The maximum number present in the list is: 5
The minumum number present in the list is: 1


In [12]:
dim = np.ndim(arr)  # to find the dimension of the array
print("The dimension of the array is:", dim)

The dimension of the array is: 1


In [15]:
shape = np.shape(arr)  # to find the shape of the array
print("The shape of the array is:", shape)
# shape (5,) means 5 element and 1 dimentional

The shape of the array is: (5,)


Change the shape of the array (e.g: Array to Matrix)

In [19]:
a = np.array([1,2,3,4,5,6,7,8,9])  # in one line make the array
a = a.reshape(3,3)  # change the shape of the array
print("The matrix from by the array is:\n", a)  # use \n for next line

The matrix from by the array is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
dim = np.ndim(a)
print("The dimension of the matrix is:", dim)

shape = np.shape(a)
print("The shape of the matrix is:", shape)  # (3,3) means the matrix is [3,3]

trace = np.trace(a)
print("The trace of the matrix is:", trace)

transpose = np.transpose(a)
print("The transpose of the matrix is:\n", transpose)

The dimension of the matrix is: 2
The shape of the matrix is: (3, 3)
The trace of the matrix is: 15
The transpose of the matrix is:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


Dot and Cross Product of two Vectors

In [5]:
A = np.array([1,2,3])
B = np.array([7,8,9])

print("First vector is:", A)
print("Second vector is:", B)

sc_product = np.dot(A,B)  # dot product of two matrix
print("The dot product of these the two vectors is:", sc_product)

vec_product = np.cross(A,B)  # cross product of two matrix
print("The cross product of these the two vectors are:", vec_product)

First vector is: [1 2 3]
Second vector is: [7 8 9]
The dot product of these the two vectors is: 50
The cross product of these the two vectors are: [-6 12 -6]


In [30]:
C = A*B
print(C)

[ 7 16 27]


Multiplication of Two Matrix

In [6]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
m1 = arr1.reshape(3,3)
print("The first matrix is:\n", m1)

arr2 = np.array([9,8,7,6,5,4,3,2,1])
m2 = arr2.reshape(3,3)
print("The second matrix is:\n", m2)

m1m2 = np.dot(m1,m2)
print("The multiplication of these two matrix is:\n", m1m2)

The first matrix is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The second matrix is:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
The multiplication of these two matrix is:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
