# Class 2

#### Inverse and determinant of a matrix

In [24]:
import numpy as np
arr = [1,2,-1,2,1,4,3,3,4]
arr = np.array(arr)
M = arr.reshape(3,3)
print("The Matrix is:\n", M)

invM = np.linalg.inv(M)
print("The Inverse of the matrix is:\n", invM)

detM = round(np.linalg.det(M))
print("The Determinant of the Matrix is:\n", detM)

The Matrix is:
 [[ 1  2 -1]
 [ 2  1  4]
 [ 3  3  4]]
The Inverse of the matrix is:
 [[ 2.66666667  3.66666667 -3.        ]
 [-1.33333333 -2.33333333  2.        ]
 [-1.         -1.          1.        ]]
The Determinant of the Matrix is:
 -3


#### Verifying the inverse is correct or not

In [9]:
# if determinant value of,
# multiplication of the matrix and the inverse of this matrix is 1
# then inverse is correct
x = np.linalg.det(np.dot(M,invM))
print(round(x))

1


#### Solution of three equation with three variables by matrix multiplication method

In [47]:
# three equations are (solve for x, y and z)
# x + 2y - z = 1
# 2x + y + 4z = 2
# 3x + 3y + 4z = 1
A = np.array([1,2,-1,2,1,4,3,3,4])
A = A.reshape(3,3)
print("Matrix A created by those equations is:\n", A)
B = np.array([1,2,1])
B = B.reshape(3,1)
print("Matrix B created by those equations is:\n", B)
invA = np.linalg.inv(A)
print("Inverse of the Matrix A is:\n", invA)

X = np.dot(invA,B)  # we use the formula: A.X = B => X = inv(A).B
print("The solution of the equation is\n", X)

Matrix A created by those equations is:
 [[ 1  2 -1]
 [ 2  1  4]
 [ 3  3  4]]
Matrix B created by those equations is:
 [[1]
 [2]
 [1]]
Inverse of the Matrix A is:
 [[ 2.66666667  3.66666667 -3.        ]
 [-1.33333333 -2.33333333  2.        ]
 [-1.         -1.          1.        ]]
The solution of the equation is
 [[ 7.]
 [-4.]
 [-2.]]


In [23]:
# direct method / solution by direct method numpy.limalg.solve(A,B)
X = np.linalg.solve(A,B)
print("The solution of the equation is\n", X)

The solution of the equation is
 [[ 7.]
 [-4.]
 [-2.]]


#### Use of command Linspace

In [26]:
P = np.linspace(1,10,4)
print(P, type(P))
# if np.linspace(i,j,n)
# use for get equidistance elements from i to j with n number of element

[ 1.  4.  7. 10.] <class 'numpy.ndarray'>


In [46]:
# formula for interval = (j-i)/(n-1)

Q = np.linspace(1,19,10)
print(Q)
interval = (19-1)/(10-1)
print("The interval is:",interval)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
The interval is: 2.0
